// =================================================================
// Cashier Domain Types — V10.2 / V10.3
// 🔒 Architecture Baseline v1.0 (LOCKED)
//
// Defines core domain types for Allocation AND Pricing.
// AllocationDraft and Pricing are SEPARATE concerns (ADR-002).
//
// Responsibility:
//   AllocationDraft  — pure batch allocation (NO sellingPrice)
//   PriceSnapshot    — pure price breakdown (sellingPrice lives HERE)
//   BatchProvider     — Repository contract (Dependency Inversion)
//   BatchPriceProvider — Pricing data contract
//
// NEVER: sellingPrice in Allocation, discount in Allocation,
//        React, Zustand, Supabase
// =================================================================

import type { ProductBatch } from "@/types/inventory";

// ─── CheckoutSession Aggregate Root (V10.4 — Domain) ───

/** CheckoutSession lifecycle states (ADR-001). */
export type SessionStatus =
  | "DRAFT"
  | "ALLOCATING"
  | "PRICED"
  | "VALIDATED"
  | "FROZEN"
  | "CANCELLED";

/**
 * CheckoutSession Aggregate Root.
 * Manages the entire checkout lifecycle from cart to frozen transaction.
 */
export interface CheckoutSession {
  /** Unique session identifier */
  sessionId: string;
  /** Reference to the active cart */
  cartId: string;
  /** Tenant context */
  tenantId: string;
  /** Branch context */
  branchId: string;
  /** Cashier user ID */
  cashierId: string;
  /** Current lifecycle state */
  status: SessionStatus;
  /** Optimistic concurrency version */
  version: number;
  /** Allocation draft (populated after allocation) */
  allocationDraft?: AllocationDraft;
  /** Price snapshot (populated after pricing) */
  priceSnapshot?: PriceSnapshot;
  /** Validation result (populated after validation) */
  validationResult?: ValidationResult;
  /** Transaction snapshot (populated after freeze — immutable) */
  transactionSnapshot?: TransactionSnapshot;
  /** ISO8601 creation timestamp */
  createdAt: string;
  /** ISO8601 last update timestamp */
  updatedAt: string;
}

// ─── Allocation Types (Domain) ───

/** Single batch entry in an allocation. PURE allocation — no price data. */
export interface AllocationEntry {
  /** Batch ID — FK to product_batches */
  batchId: string;
  /** Quantity allocated from this batch (in BASE UNIT) */
  allocatedQty: number;
  /** FEFO priority order — 1 = highest priority (earliest expiry) */
  allocationOrder: number;
}

/** Result of FEFO allocation. Mutable draft — can be rebuilt. */
export interface AllocationDraft {
  /** Unique draft identifier */
  draftId: string;
  /** Product being allocated */
  productId: string;
  /** Per-batch allocation entries (sorted by FEFO order) */
  entries: AllocationEntry[];
  /** Sum of all entries.allocatedQty */
  totalAllocated: number;
  /** ISO8601 timestamp when this draft was generated */
  generatedAt: string;
}

/** Input contract for AllocationBuilder.build(). */
export interface AllocationInput {
  /** Product to allocate for */
  productId: string;
  /** Needed quantity in BASE UNIT (e.g., 200 Tablet) */
  baseQty: number;
  /** Available batches (from Inventory — provided by caller via BatchProvider) */
  availableBatches: ProductBatch[];
}

// ─── Pricing Types (V10.3 — Domain) ───

/**
 * Single entry in a PriceSnapshot.
 * Maps one allocation entry to its pricing data.
 */
export interface PriceEntry {
  /** FK → AllocationEntry.batchId */
  batchId: string;
  /** Human-readable batch identifier (for display/receipt) */
  batchNumber: string;
  /** Selling price per BASE UNIT at snapshot time */
  sellingPrice: number;
  /** Cost price per BASE UNIT at snapshot time (HPP tracking) */
  costPrice: number;
  /** Quantity allocated from this batch (mirrors AllocationEntry) */
  allocatedQty: number;
  /** Line subtotal = sellingPrice × allocatedQty (via normalizeRupiah) */
  subtotal: number;
}

/**
 * Immutable snapshot of pricing for an entire allocation.
 * Generated by PricingEngine. SEPARATE from AllocationDraft (ADR-002).
 */
export interface PriceSnapshot {
  /** Unique snapshot identifier */
  snapshotId: string;
  /** Per-batch price entries */
  entries: PriceEntry[];
  /** Sum of all entries.subtotal */
  subtotal: number;
  /** Total discount applied (default 0) */
  discount: number;
  /** Total tax applied (default 0) */
  tax: number;
  /** Grand total = subtotal - discount + tax */
  grandTotal: number;
  /** ISO8601 timestamp when this snapshot was generated */
  generatedAt: string;
}

/** Input contract for PricingEngine.calculate(). */
export interface PricingInput {
  /** Allocation to price (from AllocationBuilder) */
  allocationDraft: AllocationDraft;
  /** Provider for per-batch pricing data */
  priceProvider: BatchPriceProvider;
}

// ─── Pricing Rule Types (V10.3 — extensible for future) ───

/**
 * Pricing rule contract — pluggable strategy for discounts/promos/tax.
 * Empty for now (V10.3: standard pricing only).
 * Future: PromoPricing, MemberPricing, BPJSPricing implement this.
 */
export interface PricingRule {
  /** Rule identifier for audit trail */
  readonly ruleId: string;
  /** Human-readable rule name */
  readonly ruleName: string;
  /** Apply this rule to a list of price entries. Returns modified entries. */
  apply(entries: PriceEntry[]): PriceEntry[];
}

// ─── Repository Contracts (Dependency Inversion) ───

/**
 * Contract for batch data access.
 * Domain defines this interface. Infrastructure implements it.
 * This keeps the Domain Layer independent of Supabase/Zustand/React.
 */
export interface BatchProvider {
  /** Get all batches for a product (with quantity > 0) */
  getBatchesByProduct(productId: string): ProductBatch[];
  /** Get a single batch by ID */
  getBatchById(batchId: string): ProductBatch | undefined;
}

/**
 * Contract for batch pricing data access.
 * Domain defines this interface. Infrastructure implements it.
 * Separate from BatchProvider — PricingEngine only needs price data.
 */
export interface BatchPriceProvider {
  /** Get the selling price for a given batch */
  getSellingPrice(batchId: string): number;
  /** Get the cost price for a given batch (HPP tracking) */
  getCostPrice(batchId: string): number;
}

// ─── Validation Types (V10.3 — Domain) ───

/** Type of validation issue detected. */
export type ValidationIssueType =
  | "STOCK_CHANGED"
  | "BATCH_MISSING"
  | "BATCH_EXPIRED";

/** A single validation issue — explains what changed. */
export interface ValidationIssue {
  /** Issue category */
  type: ValidationIssueType;
  /** Which batch is affected */
  batchId: string;
  /** Human-readable description of the change */
  description: string;
  /** Allocated quantity from the draft */
  allocatedQty: number;
  /** Current quantity in inventory (for STOCK_CHANGED) */
  currentQty?: number;
}

/** Result of allocation validation. */
export interface ValidationResult {
  /** Overall validation status */
  status: "VALID" | "INVALID";
  /** ISO8601 timestamp when checked */
  checkedAt: string;
  /** List of issues (empty if VALID) */
  issues: ValidationIssue[];
}

/** Input contract for AllocationValidator.validate(). */
export interface ValidationInput {
  /** Allocation draft to validate against current inventory */
  allocationDraft: AllocationDraft;
  /** Current batch snapshot from inventory */
  currentBatches: ProductBatch[];
  /** Reference date for expiry check (default: now) */
  referenceDate?: Date;
}

/** Contract for inventory snapshot provider (Dependency Inversion). */
export interface InventorySnapshotProvider {
  /** Get current batch state for comparison */
  getCurrentBatches(productId: string): ProductBatch[];
}

// ─── Freezer Types (V10.4 — Domain) ───

/** Immutable snapshot of a single cart item at freeze time. */
export interface FrozenTransactionItem {
  /** Product identifier */
  productId: string;
  /** Product display name at freeze time */
  productName: string;
  /** Quantity in base unit at freeze time */
  baseQuantity: number;
  /** Unit price per base unit at freeze time */
  baseUnitPrice: number;
  /** Display unit selected by cashier */
  selectedUnitCode?: string;
  /** Per-batch allocation snapshot (from AllocationDraft) */
  batchAllocations: FrozenBatchAllocation[];
  /** Line subtotal for this item */
  subtotal: number;
}

/** Batch allocation entry frozen in a transaction. */
export interface FrozenBatchAllocation {
  /** Batch ID */
  batchId: string;
  /** Batch number */
  batchNumber: string;
  /** Quantity allocated from this batch */
  allocatedQty: number;
  /** Selling price per base unit */
  sellingPrice: number;
  /** Cost price per base unit (HPP) */
  costPrice: number;
}

/** Payment record frozen in a transaction. */
export interface FrozenPayment {
  /** Payment amount */
  amount: number;
  /** Payment method */
  method: "cash" | "debit" | "credit" | "qris" | "transfer";
  /** Optional reference number */
  ref?: string;
  /** Optional wallet ID */
  walletId?: string;
}

/**
 * Immutable transaction snapshot.
 * Generated by TransactionFreezer. After freeze, this CANNOT be modified.
 */
export interface TransactionSnapshot {
  /** Unique snapshot identifier */
  snapshotId: string;
  /** Transaction ID */
  transactionId: string;
  /** Invoice number */
  invoiceNumber: string;
  /** Frozen cart items */
  items: FrozenTransactionItem[];
  /** Frozen payments */
  payments: FrozenPayment[];
  /** Subtotal (sum of all line subtotals) */
  subtotal: number;
  /** Discount applied */
  discount: number;
  /** Tax applied */
  tax: number;
  /** Grand total = subtotal - discount + tax */
  total: number;
  /** Cashier display name */
  cashierName: string;
  /** Pharmacy / branch ID */
  pharmacyId: string;
  /** Cashier user ID */
  cashierId: string;
  /** ISO8601 timestamp when frozen */
  frozenAt: string;
}

/** Input contract for TransactionFreezer.freeze(). */
export interface FreezeInput {
  /** Cart items to freeze (canonical fields) */
  cartItems: {
    productId: string;
    productName: string;
    baseQuantity: number;
    baseUnitPrice: number;
    selectedUnitCode?: string;
    allocationDraft?: AllocationDraft;
    priceSnapshot?: PriceSnapshot;
  }[];
  /** Payments collected */
  payments: { amount: number; method: string; ref?: string; walletId?: string }[];
  /** Transaction metadata */
  transactionId: string;
  invoiceNumber: string;
  cashierName: string;
  pharmacyId: string;
  cashierId: string;
}
